name: PR Auto Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - uses: actions/checkout@v4
        with:
          repository: samrat-dev01/pr-reviewer
          ref: v1.0.0
          path: .pr-reviewer
          # token: ${{ secrets.REVIEWER_REPO_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci --ignore-scripts
        working-directory: .pr-reviewer

      - run: npm run review:pr
        working-directory: .pr-reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPOSITORY: ${{ github.repository }}
          REPO_ROOT: ${{ github.workspace }}
          LLM_BASE_URL: https://ollama.com
          LLM_MODEL: gpt-oss:120b-cloud
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}